try smaller ones again

diff --git a/nutrinova-ui/Dockerfile b/nutrinova-ui/Dockerfile
--- a/nutrinova-ui/Dockerfile
+++ b/nutrinova-ui/Dockerfile
@@ -1,62 +1,40 @@
-FROM node:20-alpine AS base
+FROM node:21-alpine AS base
 
-ARG NUTRINOVA_API_URL
-ENV NUTRINOVA_API_URL=$NUTRINOVA_API_URL
 
-# Install dependencies only when needed
-FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 RUN apk add --no-cache libc6-compat
 WORKDIR /app
-
-# Install dependencies based on the preferred package manager
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
-
-
-# Rebuild the source code only when needed
-FROM base AS builder
-WORKDIR /app
-COPY --from=deps /app/node_modules ./node_modules
 COPY . .
+# Install dependencies based on the preferred package manager
+RUN npm install -g npm@latest
+RUN npm ci
 
 # Next.js collects completely anonymous telemetry data about general usage.
 # Learn more here: https://nextjs.org/telemetry
 # Uncomment the following line in case you want to disable telemetry during the build.
 ENV NEXT_TELEMETRY_DISABLED 1
 
-# RUN yarn build
-
 # If using npm comment out above and use below instead
-RUN npm install -g npm@latest
-RUN npm run build
+RUN npm run build || { echo "Build failed, outputting logs"; for f in /root/.npm/_logs/*; do echo "Outputting $f"; cat "$f"; done; exit 1; }
+
 
 # Production image, copy all the files and run next
 FROM base AS runner
 WORKDIR /app
 
+COPY --from=base /app .
+
 ENV NODE_ENV production
+ARG NUTRINOVA_API_URL
+ENV NUTRINOVA_API_URL=$NUTRINOVA_API_URL
 # Uncomment the following line in case you want to disable telemetry during runtime.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
 RUN addgroup --system --gid 1001 nodejs
 RUN adduser --system --uid 1001 nextjs
 
-COPY --from=builder /app/public ./public
-
 # Set the correct permission for prerender cache
-RUN mkdir .next
 RUN chown nextjs:nodejs .next
-
-# Automatically leverage output traces to reduce image size
-# https://nextjs.org/docs/advanced-features/output-file-tracing
-COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
 USER nextjs
 
